### ISSUE TITLE
how can i get the permission for EmotionVideo-8 dataset in google drive？

### ISSUE THREAD

**Issue by nekodevelopers** [maysonma/VAANet#17]
i am a graduate student from South China Normal University and want to recurrent VAANet in my device， but i can not get the permission for EmotionVideo-8 dataset，so what is the procedure for applying for dataset？

**Comment by ChenyuLy** [comment]
> i am a graduate student from South China Normal University and want to recurrent VAANet in my device， but i can not get the permission for EmotionVideo-8 dataset，so what is the procedure for applying for dataset？

请问你找到数据集了吗

**Comment by CaoHoangTung** [comment]
Hi, I cannot access the google drive link as well. How can I ask for the permission?
