### ISSUE TITLE
pytorch version

### ISSUE THREAD

**Issue by Lzvvvvv** [maysonma/VAANet#5]
the version of Pytorch written in the readme needs to be 0.4+. Is 0.4 OK?

**Comment by maysonma** [comment]
I am quite sure that the code cannot run on 0.4.0, so please use 0.4.1 at least.

**Comment by Lzvvvvv** [comment]
> I am quite sure that the code cannot run on 0.4.0, so please use 0.4.1 at least.

OK,thanks for your reply!
