### ISSUE TITLE
Output file #0 does not contain any stream

### ISSUE THREAD

**Issue by camCX** [maysonma/VAANet#8]
Hey,

Sorry to be a bother. But I need your help. 

I successfully installed the requirements with pip. But when I convert from mp4 to mp3 files using /tools/video2mp3.py, I got an error message:

`Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '4599847220_ff1719b818_700.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isom
    creation_time   : 2010-05-11T21:51:52.000000Z
  Duration: 00:00:05.64, start: 0.000000, bitrate: 653 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv), 176x144 [SAR 1:1 DAR 11:9], 649 kb/s, 25 fps, 25 tbr, 25k tbn, 50 tbc (default)
    Metadata:
      creation_time   : 2010-05-11T21:51:52.000000Z
      handler_name    : MP4 Video Media Handler
      encoder         : AVC Coding
Output #0, mp3, to '4599847220_ff1719b818_700.mp3':
Output file #0 does not contain any stream`

So, I can't get the mp3 files for such mp4 files，cause they without sound. And When I run `python main.py`, I got an `AssertionError: ～/VAANet/datasets/VideoEmotion/mp3/Fear/4599847220_ff1719b818_700.mp3`. 

How to solve this problem？

Thanks!

Here is the list of these videos without sound:

18 video：

Anger/5398817861_aab3f3ccc3_700.mp4

Disgust/2919246884_98d36ac5f8_700.mp4

Disgust/3066020031_3ce96234c4_700.mp4

Disgust/6987110310_363986cfb7_700.mp4

Disgust/4653815988_6c3fa68727_700.mp4

Disgust/4321792116_dbac38ea64_700.mp4

Disgust/5038117109_85396cf87e_700.mp4

Disgust/4997016067__700.mp4

Disgust/5762574190_9bc4053087_700.mp4

Disgust/6973240238_2273917d90_700.mp4

Sadness/4454167796_a0935f294d_700.mp4

Trust/2713649728_89eeb833e5_700.mp4

Fear/4599847220_ff1719b818_700.mp4

Fear/2400533643_42b4677a49_700.mp4

Fear/5111653779_856b2f9397_700.mp4

Fear/2401021188_38d4114a26_700.mp4

Fear/2421576400_8aece21822_700.mp4

Fear/3114323439_98c5f04dcc_700.mp4

**Comment by 777Rebecca** [comment]
Hello, I also encountered the same problem, how did you solve it?

**Comment by jhyukjang** [comment]
I also encountered this issue. How to solve this problem?
